name: Build & Qodana
on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java Setup
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 17

      - name: Gradle Setup
        uses: gradle/actions/setup-gradle@v4

      #     This fucking broke again
      #      - name: Validate Wrapper Integrity
      #        uses: gradle/actions/wrapper-validation@v3

      - name: Q&D Fix
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

      - name: Get Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs

  qodana:
    runs-on: ubuntu-latest
    needs: build  # run Qodana after the build succeeds
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0

      - name: Java Setup
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 17

      - name: Gradle Setup
        uses: gradle/actions/setup-gradle@v4

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.2
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_979676491 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'